services:
  - name: nodejs-app
    type: web
    env: node
    buildCommand: npm install
    startCommand: npm start
    branch: main
    region: oregon  # Change to your preferred region
    plan: free      # Change to 'starter' or 'pro' for paid plans
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString

databases:
  - name: postgres-db
    plan: free        # Change to 'starter' or 'pro' for paid plans
    region: oregon    # Match this to your app region
    properties:
      defaultDatabase: app_db
      defaultUser: app_user
