# This is a basic example Blueprint for a Django web service and
# the PostgreSQL database it connects to.
services:
  - type: web # A Python web service named django-app running on a free instance
    plan: free
    name: cloud-app
    runtime: node
    repo: https://github.com/Abdellatifzidane/app-cloud.git
    buildCommand: npm install
    startCommand: npm start
    region : frankfurt
    envVars:
      - key: DATABASE_URL # Sets DATABASE_URL to the connection string of the django-app-db database
        fromDatabase:
          name: cloud-db
          property: connectionString

databases:
  - name: cloud-db # A PostgreSQL database named django-app-db running on a free instance
    region : frankfurt
    plan: free